/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        bg: 'var(--color-bg)',
        'bg-2': 'var(--color-bg-2)',
        surface: 'var(--color-surface)',
        'surface-2': 'var(--color-surface-2)',
        'surface-3': 'var(--color-surface-3)',
        'surface-4': 'var(--color-surface-4)',
        'surface-5': 'var(--color-surface-5)',
        'surface-6': 'var(--color-surface-6)',
        border: 'var(--color-border)',
        'border-md': 'var(--color-border-md)',
        'border-strong': 'var(--color-border-strong)',
        primary: 'var(--color-primary)',
        'primary-hover': 'var(--color-primary-hover)',
        'primary-dim': 'var(--color-primary-dim)',
        'primary-ring': 'var(--color-primary-ring)',
        accent: 'var(--color-accent)',
        'accent-dim': 'var(--color-accent-dim)',
        'on-surface': 'var(--color-on-surface)',
        'on-muted': 'var(--color-on-muted)',
        'on-dim': 'var(--color-on-dim)',
        success: 'var(--color-success)',
        'success-dim': 'var(--color-success-dim)',
        error: 'var(--color-error)',
        'error-dim': 'var(--color-error-dim)',
        warning: 'var(--color-warning)',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        lg: '1rem',
        xl: '1.25rem',
        '2xl': '1.5rem',
      },
      backgroundImage: {
        'gradient-ai': 'linear-gradient(135deg, #6366f1 0%, #06b6d4 100%)',
        'gradient-ai-soft': 'linear-gradient(135deg, rgba(99,102,241,0.12) 0%, rgba(6,182,212,0.12) 100%)',
        'gradient-radial-primary': 'radial-gradient(ellipse at center, rgba(99,102,241,0.18) 0%, transparent 70%)',
        'gradient-radial-accent': 'radial-gradient(ellipse at top left, rgba(99,102,241,0.15) 0%, rgba(6,182,212,0.08) 50%, transparent 80%)',
      },
      boxShadow: {
        glow: 'var(--shadow-glow)',
        'glow-sm': 'var(--shadow-glow-sm)',
        'glow-accent': 'var(--shadow-glow-accent)',
        card: 'var(--shadow-card)',
        modal: 'var(--shadow-modal)',
      },
      animation: {
        'fade-in': 'fadeIn 0.35s ease both',
        'fade-up': 'fadeUp 0.45s ease both',
        'scale-in': 'scaleIn 0.25s ease both',
        'pulse-glow': 'pulseGlow 2s ease-in-out infinite',
        'bounce-dot': 'bounceDot 1.4s ease-in-out infinite both',
        shimmer: 'shimmer 1.6s linear infinite',
        spin: 'spin 0.7s linear infinite',
        float: 'float 5s ease-in-out infinite',
        'blob-move': 'blobMove 14s ease-in-out infinite',
        marquee: 'marquee 28s linear infinite',
      },
      keyframes: {
        fadeIn: { from: { opacity: '0' }, to: { opacity: '1' } },
        fadeUp: { from: { opacity: '0', transform: 'translateY(14px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        scaleIn: { from: { opacity: '0', transform: 'scale(0.96)' }, to: { opacity: '1', transform: 'scale(1)' } },
        pulseGlow: { '0%,100%': { boxShadow: '0 0 20px rgba(99,102,241,0.15)' }, '50%': { boxShadow: '0 0 40px rgba(99,102,241,0.3)' } },
        bounceDot: { '0%,80%,100%': { transform: 'scale(0.6)', opacity: '0.4' }, '40%': { transform: 'scale(1)', opacity: '1' } },
        shimmer: { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
        spin: { to: { transform: 'rotate(360deg)' } },
        float: { '0%,100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-10px)' } },
        blobMove: { '0%,100%': { transform: 'translate(0, 0) scale(1)' }, '33%': { transform: 'translate(4%, 6%) scale(1.08)' }, '66%': { transform: 'translate(-3%, -4%) scale(0.96)' } },
        marquee: { from: { transform: 'translateX(0)' }, to: { transform: 'translateX(-50%)' } },
      },
    },
  },
  plugins: [],
}
