<?php

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Serves /llms.txt — a curated, markdown summary of the site written for
 * LLMs/generative search engines to consume (the GEO equivalent of
 * robots.txt). Content is generated by Kaelah AI and stored here; this
 * class serves it directly on 'init', without relying on rewrite rules or
 * a permalink flush.
 *
 * Also acts as a reliability fallback for /robots.txt: on some hosting
 * setups (e.g. WordPress installed in a subdirectory) WordPress's own
 * virtual robots.txt route (is_robots()/do_robots(), normally triggered on
 * 'template_redirect') fails to match the request. Intercepting the path
 * ourselves, earlier, on 'init', guarantees it is always served — still via
 * do_robots(), so every other plugin's `robots_txt` filter (including
 * Kaelah_Frontend's AI-crawler allow rules) still applies normally.
 */
class Kaelah_Llms_Txt {

	private static $instance = null;

	public static function instance() {
		if ( null === self::$instance ) {
			self::$instance = new self();
		}
		return self::$instance;
	}

	private function __construct() {
		add_action( 'init', array( $this, 'maybe_serve_llms_txt' ) );
		add_action( 'init', array( $this, 'maybe_serve_robots_txt' ) );
	}

	private function request_path() {
		return wp_parse_url( esc_url_raw( $_SERVER['REQUEST_URI'] ?? '' ), PHP_URL_PATH );
	}

	public function maybe_serve_llms_txt() {
		$content = get_option( 'kaelah_llms_txt' );
		if ( empty( $content ) ) {
			return;
		}

		$expected_path = wp_parse_url( home_url( '/llms.txt' ), PHP_URL_PATH );
		if ( $this->request_path() !== $expected_path ) {
			return;
		}

		header( 'Content-Type: text/plain; charset=utf-8' );
		echo $content; // phpcs:ignore WordPress.Security.EscapeOutput -- plain text output, not HTML.
		exit;
	}

	public function maybe_serve_robots_txt() {
		$expected_path = wp_parse_url( home_url( '/robots.txt' ), PHP_URL_PATH );
		if ( $this->request_path() !== $expected_path ) {
			return;
		}

		do_robots();
		exit;
	}
}
